# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION: 'free'
  RESOURCE_GROUP: 'Madhu_testing'
  CONTAINER_APP: 'containertest'
  CONTAINER_IMAGE: 'simple-hello-world-container'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Updating container app with new image"
          az containerapp update --name $(CONTAINER_APP) --resource-group $(RESOURCE_GROUP) --image $(CONTAINER_IMAGE)
      displayName: 'Update Container App Image'


